server:
  port: 8763
  servlet:
    context-path: /provider

#provider服务注册到eureka中的服务名称
spring:
  application:
    name: provider

eureka:
  client:
    erviceUrl:
     defaultZone: http://http://localhost:8761/eureka